### ISSUE TITLE
Example scripts need namespaces to prevent conflicts

### ISSUE THREAD

**Issue by umutkutlu** [thirdweb-dev/unity-sdk#103]
### Issue Definition
Scripts that are located in the `Thirdweb/Examples` folder do not have namespaces, which can sometimes cause conflicts with other Unity assets. 
In my case, [Thirdweb's Debugger](https://github.com/thirdweb-dev/unity-sdk/blob/main/Assets/Thirdweb/Examples/Scripts/Utils/Debugger.cs) conflicts with the [DOTween's Debugger](https://github.com/Demigiant/dotween/blob/develop/_DOTween.Assembly/DOTween/Core/Debugger.cs).

### Suggested Solution:
To resolve this issue, the Thirdweb SDK should add namespaces to the example scripts. This will help to prevent conflicts with other Unity assets.

**Comment by 0xFirekeeper** [comment]
Absolutely, will get that merged next release, thanks for making a PR!
