### ISSUE TITLE
Cannot connect my Metamask wallet using connect wallet prefab on built android app

### ISSUE THREAD

**Issue by Thomas107500** [thirdweb-dev/unity-sdk#105]
Encountered similar problem in #90  , It works while i run it in the editor but not on the built app, my app is an Android app, i build it using mono (can confirm IL2CPP crash the app, more detail below) i used the connect wallet prefab, the qr code and the buttons are all responsive, the deeplink successfully opened metamask on my phone, metamask did show connecting message, but then it just disappeared, not asking me to sign anything, i waited a few seconds then close the metamask app and switched back to my app, it didnt crash but nothing happened, there are a few occasions my app suddenly opened metamask after i tried going back and forth my app and metamask and it ask me to allow access, i allowed access and back to app the qr code screen did disappear, but the connect wallet button did not change to the UI component that display balance etc.

Here is the log i get when running on my phone
![image](https://github.com/thirdweb-dev/unity-sdk/assets/49201909/3da45e21-29f1-4777-805a-fcfe973a31e6)

For IL2CPP, it will crash after i come back to the app after deeplink opened metamask, no option to sign in metamask either

**Comment by 0xFirekeeper** [comment]
We're aware of the issues on mobile and have updated the MM SDK, however wallet pausing/disconnection/crashing issues remain so we haven't shipped it (https://github.com/thirdweb-dev/unity-sdk/pull/101). We're in communication with the Metamask team to get it resolved.

**Comment by ravikiran895** [comment]
When can we expect this Resolved SDK from Thirdweb. Please update

**Comment by 0xFirekeeper** [comment]
Should be fixed in [this release](https://github.com/thirdweb-dev/unity-sdk/releases/tag/v3.0.0-beta.12)

**Comment by Heshambb** [comment]
As you've explained in your video you have mentioned there is a prefab for thirdwebmanager but i did't saw it on your package

**Comment by 0xFirekeeper** [comment]
`WalletProvider_Metamask` - it's under "Danger Zone" in the ThirdwebManager
It was available previously, but just got updated a little, you can look for it in your project files too

**Comment by 0xFirekeeper** [comment]
Going to close this, feel free to reach out on Discord if you have questions about the prefab or others, thanks!
