### ISSUE TITLE
Bundle size of thirdweb-unity-bridge.js exceeds 9.5MB

### ISSUE THREAD

**Issue by coding-velociraptor** [thirdweb-dev/unity-sdk#107]
Hey, 

Thank you for your hard working on making Thirdweb available in Unity. It allowed us to integreate blockchain operations into our WebGL-based game easily.

During deployment, we noticed thirdweb-unity-bridge.js exceeeds 9.5MB in size. We are currently looking into improving loading times for players and this seems to be a good candidate. This is a major blocker for rolling out to a large, mostly mobile audience. Are there any plans to work on the bundled size? 

How do you build this artifact? 

Thank you, 
CV.

**Comment by 0xFirekeeper** [comment]
Sure thing
- pull the js repo
- install dependencies
- update the [bridge](https://github.com/thirdweb-dev/js/blob/main/packages/unity-js-bridge/src/thirdweb-bridge.ts) code with your changes
- `yarn build` will generate the js under ./dist
- copy the js and paste it into [this file](https://github.com/thirdweb-dev/unity-sdk/blob/main/Assets/WebGLTemplates/Thirdweb/lib/thirdweb-unity-bridge.js) in your Unity project

**Comment by coding-velociraptor** [comment]
If you are curious, here is a bundle analyzer snapshot:
<img width="1044" alt="image" src="https://github.com/thirdweb-dev/unity-sdk/assets/96731828/6edfab85-13ec-4a6e-a08d-45cac2c9cc66">
