### ISSUE TITLE
Expose optional gateway url for ERC721

### ISSUE THREAD

**Issue by 0xFirekeeper** [thirdweb-dev/unity-sdk#11]
ERC721.metadata.image using our own gateway would be cool for heavier applications.

ERC721.Get/GetOwned/GetAll having that param exposed would be useful if possible!

**Comment by joaquim-verges** [comment]
just merged a change that allows you overriding the default IPFS gateway in the SDK options.

example:
```csharp
var sdk = new ThirdwebSDK("goerli", new ThirdwebSDK.Options()
{
    ipfsGatewayUrl = "https://gateway.pinata.cloud/ipfs/"
});
```

just make sure the url ends in /ipfs/ (standard)

lmk if that works for you!

**Comment by 0xFirekeeper** [comment]
Works great! Much appreciated ser.
