### ISSUE TITLE
wallet.transfer problem at v4.2.2 in unity 2023

### ISSUE THREAD

**Issue by mohammadriyahi** [thirdweb-dev/unity-sdk#137]
I tried to use wallet.transfer like this line:
 var data = await sdk.wallet.Transfer("0xABCDEFGHIJKLMNOPQRSDUVWXYZ", "100", "ExampleAddress");
 but its not working
I put function of this on button and its still does nothing
 its not working at all
 if its a general problem and you should fix this
 do it ASAP plz
 and if you think its only happend for me , say and then i explain more of my code here to get your helps
 thanks  heroes :D

**Comment by 0xFirekeeper** [comment]
Hi @mohammadriyahi which wallet/network were you using?
