### ISSUE TITLE
Getting null reference error while calling marketplace.directlisting.GetAll();

### ISSUE THREAD

**Issue by vinmeena** [thirdweb-dev/unity-sdk#145]
![Untitled](https://github.com/thirdweb-dev/unity-sdk/assets/34139294/b4d76dd5-ea2d-455a-a181-0fe72c5125e9)
![Untitled_1](https://github.com/thirdweb-dev/unity-sdk/assets/34139294/2b852541-f4f1-41a3-b91e-8e5d5a7ec6da)
![Untitled_3](https://github.com/thirdweb-dev/unity-sdk/assets/34139294/84d9e99c-8f69-44ad-83bb-81b540d35642)

These Screenshot contains all the required details. I'm not able to find any solution of it. Please help me out Or
If I'm doing something wrong please let me know.

**Comment by 0xFirekeeper** [comment]
Hey, would need to know the contract address to figure out why the return value is null in this case, gut feeling says this is probably an ERC1155 that doesn't have the functions we're trying to query or differently named. Alternatively you can always use `var result = await contract.Read<YourReturnType>("function", param1, param2, ...);`

**Comment by vinmeena** [comment]
@0xFirekeeper 
Here's Contract Address : "0x393a987935E99979Af087b3781156B6960698644"
It's Marketplace Contract with 3 Direct Listings.

**Comment by vinmeena** [comment]
Sure, Thanks for helping out!

**Comment by 0xFirekeeper** [comment]
Fixed in https://github.com/thirdweb-dev/unity-sdk/commit/413324a4862de30baa87e83c6a822cdd94748a6e

**Comment by 0xFirekeeper** [comment]
Shipped in [4.4.1](https://github.com/thirdweb-dev/unity-sdk/releases/tag/v4.4.1)
