### ISSUE TITLE
Framework 'Pods_UnityFramework' not found

### ISSUE THREAD

**Issue by andyspeak1993** [thirdweb-dev/unity-sdk#150]
added the package to our project works on Windows and Mac but getting "Framework 'Pods_UnityFramework' not found" when building for IOS any suggestions?

**Comment by 0xFirekeeper** [comment]
Hi @andyspeak1993 !
Please see our mobile build instructions [here.](https://github.com/thirdweb-dev/unity-sdk/tree/v4.6.4?tab=readme-ov-file#mobile)
In your case make sure Embedded Frameworks in XCode contains everything needed.

**Comment by andyspeak1993** [comment]
hey sorry for the slow response, i checked and embedded frameworks are missing "Framework 'Pods_UnityFramework' both MetaMask or Starscream mentioned in the instructions are present
