### ISSUE TITLE
Assembly error

### ISSUE THREAD

**Issue by OmeGaCinoS** [thirdweb-dev/unity-sdk#155]
Hi! In your latest version 4.7.3 I got an error with two time the same assembly in Unity "Newtonsoft.Json.dll"

![image](https://github.com/thirdweb-dev/unity-sdk/assets/5391554/27692b2a-080b-4d44-b44d-0fd227587903)

**Comment by 0xFirekeeper** [comment]
Hey @OmeGaCinoS  please refer to the [installation guide](https://github.com/thirdweb-dev/unity-sdk?tab=readme-ov-file#installation) - Newtonsoft can come as part of your Unity base packages in some versions, feel free to remove the one that is part of our package and that should fix it!

**Comment by OmeGaCinoS** [comment]
It's actually not working for me, have 90 mores error xD But maybe due to my Unity version I'm on 2020.3.46

**Comment by 0xFirekeeper** [comment]
Ah yes we don't officially support 2020 will need to resolve additional conflicts or add libraries for that one, depending on the error
