### ISSUE TITLE
Astar zkEVM(chainID:3776) doesn't work in Unity

### ISSUE THREAD

**Issue by issihiki** [thirdweb-dev/unity-sdk#159]
I am creating a game and using third web's unitysdk, but the newly released chain ID (3776) of AstarZKEVM in thirdwebmaneger is not recognized and an error occurs. How long will it take to get a newly released chain ID?
![imag1e](https://github.com/thirdweb-dev/unity-sdk/assets/127279333/f20c8e43-5832-444f-b4bb-0f9a9e3e6f17)

![image](https://github.com/thirdweb-dev/unity-sdk/assets/127279333/1b0b2604-a1eb-406d-92bc-e8ca7806c4f5)

**Comment by warengonzaga** [comment]
Hello @0xFirekeeper can you take a look into this if this is possible to add?

Also @issihiki do you have the full info of the RPC in question?

**Comment by 0xFirekeeper** [comment]
Null ref seems harsh in this scenario, will improve behavior for new unknown chains. 
Will also create a release today with a chains package update and will make sure to include AstarZKEVM!

**Comment by 0xFirekeeper** [comment]
Here you go @issihiki https://github.com/thirdweb-dev/unity-sdk/releases/tag/v4.7.10
Thank you for the report!
