### ISSUE TITLE
Problem with IOS Build

### ISSUE THREAD

**Issue by AwsomeSauci** [thirdweb-dev/unity-sdk#168]
I download ThirdWeb SDK, import in empty unity project, build for IOS, when i build in xcode i have this error

Desktop/buildCC/Libraries/Thirdweb/Core/Plugins/MetaMask/Plugins/iOS/UnityWebSocket/MetaMaskAppController.mm:10:9 'MetaMask_iOS/WebSocketProvider.h' file not found

**Comment by 0xFirekeeper** [comment]
`Double click on main.unitypackage under Assets\Thirdweb\Plugins\MetaMask\Installer\Packages and reimport the iOS folder`
Which version are you on? Recent versions should no longer have this issue.

**Comment by AwsomeSauci** [comment]
i fix this with update to last version SDK, reimport IOS from Metamask, and add pods framework in xcode in build phases
