### ISSUE TITLE
Smart contract transactions on IOS

### ISSUE THREAD

**Issue by AwsomeSauci** [thirdweb-dev/unity-sdk#171]
smart contract transactions work fine in Unity, they work fine in the Android build, but when launched on iOS, a connection to the wallet occurs, but then the transaction is not sent.

**Comment by AwsomeSauci** [comment]
i send transaction to MetaMask and connect with Metamask

**Comment by 0xFirekeeper** [comment]
Try clearing your MM connections from the mobile app settings (or experimental wc sessions if using wc) and restarting the app - if that still doesn't work please provide more info about your build and os settings / any potential error messages you see / file a support ticket on our website. Thanks!

**Comment by AwsomeSauci** [comment]
Clearing MM connections doesn't work, i use IOS version 17.4.1, XCODE 15.3. I build project in unity with default ios buld settings, in XCODE just add pods framework in build phases.

**Comment by AwsomeSauci** [comment]
Everything works fine in the unity editor and in the android build. The problem is with the iOS build.

**Comment by 0xFirekeeper** [comment]
Hey @AwsomeSauci apologies for the late reply had the chance to build this repo and test on iOS again
If you make sure Metamask is closed before you connect, then connect using the deep link, does the problem persist? My mm seems to automatically open on connection, message signature and transaction signature.
I did not make any edits in xcode post build and used our recommended ios build settings in Unity.
XCode version 15.1 (15C65) on my end.

**Comment by AwsomeSauci** [comment]
mm connects to the application via deeplink, but then transactions don't go through, I'll try again with a newer version of the SDK. If it doesn't work on the new version, then I'll try to build a new project with only the thirdWeb library.

**Comment by 0xFirekeeper** [comment]
Sounds good, I think this is mostly related to how MM is launched. If the problem persists if MM was closed before connecting do let me know. If it was launched by the game then the game should be able to auto reopen mm mobile app every time an action is taken.

**Comment by 0xFirekeeper** [comment]
MM is coming out with v2.0 soon, please reopen a ticket after the upgrade if this still persists on your end, we'll be monitoring.
