### ISSUE TITLE
error CS1503: Argument 3: cannot convert from 'double[]' to 'decimal[]'

### ISSUE THREAD

**Issue by OmeGaCinoS** [thirdweb-dev/unity-sdk#176]
I got this error : 

Assets\Thirdweb\Core\Scripts\Utils.cs(612,173): error CS1503: Argument 3: cannot convert from 'double[]' to 'decimal[]'

This correspond to this line : 

 var feeHistory = await web3.Eth.FeeHistory.SendRequestAsync(new Nethereum.Hex.HexTypes.HexBigInteger(20), Nethereum.RPC.Eth.DTOs.BlockParameter.CreateLatest(), new double[] { 20 });

Have you a fix about this?

**Comment by 0xFirekeeper** [comment]
Hey @OmeGaCinoS which chain is this on?

**Comment by 0xFirekeeper** [comment]
I mean which blockchain

**Comment by OmeGaCinoS** [comment]
Oh I will make token in ERC-20, so I think it's MainNet? Not sure

**Comment by 0xFirekeeper** [comment]
What is the "active chain" in your ThirdwebManager? Alternatively you can send me the link to your token if you have one :)

**Comment by OmeGaCinoS** [comment]
Sorry I'm not sure to see where is this? I check ThirdwebManager, but I see a prefab that I can't click on it! 

I just install the package, and he gives me this error at the start, I don't use it already, so I'm not sure how it works, I was waiting to have it working in my project and continue to watch the tutorial after
