### ISSUE TITLE
Including Starscream as dependency twice

### ISSUE THREAD

**Issue by coding-velociraptor** [thirdweb-dev/unity-sdk#181]
Hey,

I noticed that Starscream is included into the package twice:

1. In [MetaMaskDependencies.xml](https://github.com/thirdweb-dev/unity-sdk/blob/main/Assets/Thirdweb/Core/Plugins/MetaMask/Editor/MetaMaskDependencies.xml#L81) leads an entry in the Podfile
2. As Starscream.framework under `/Plugins/iOS/iphoneos` 

In our setup, it fails the build. At the moment, we manually delete on of them. Wouldn't it better to only keep the first one? 

XCode 15.3
OS X 14 (arm64)

Thanks.

**Comment by 0xFirekeeper** [comment]
Will look at this soon, I don't remember getting duplicates in my build process but that's a good callout - are you using Unity 2021 by chance?

**Comment by coding-velociraptor** [comment]
We use [Unity 2022.3.10f1](https://unity3d.com/de/get-unity/download/archive) right now.

**Comment by 0xFirekeeper** [comment]
Decided to remove the pod instead. After the next MetaMask upgrade might do the opposite. Thanks for the report, should be fixed here https://github.com/thirdweb-dev/unity-sdk/releases/tag/v4.13.3
