### ISSUE TITLE
Coinbase Wallet on mobile apps

### ISSUE THREAD

**Issue by coding-velociraptor** [thirdweb-dev/unity-sdk#183]
Hey,

I was wondering if there are any plans to include Coinbase Wallet connector for mobile apps on iOS and Android. I'm aware they only work on WebGL right now. However, I also saw there are official platform packages:

https://docs.cloud.coinbase.com/wallet-sdk/docs/ios-install 
and 
https://docs.cloud.coinbase.com/wallet-sdk/docs/android-install

Recently, we have observered a high interest in Base and Coinbase. In fact, we have many players who had to jump through hoops to connect an alternative wallet solution on their mobile app to play.

Thank you in advance, 
CV

**Comment by 0xFirekeeper** [comment]
Have a couple things to get to first but native Coinbase support has definitely been on the todo list.

If by the time I reach that ticket they haven't integrated in .NET I might write up a mini .NET plugin on their behalf to communicate with their native libraries.

Can't give an exact ETA sadly as I'm going to be implementing some prioritized thirdweb features soon followed by work on Unity v5 and .NET SDK.

I'll try to fast track this and explore a quick path forward though, thanks for the feedback.
