### ISSUE TITLE
I had an error while packing and running

### ISSUE THREAD

**Issue by haokunABC** [thirdweb-dev/unity-sdk#186]
I just imported the package into the project and didn't do anything. I just changed WebGL temple according to the Settings of the official website. When he finished the package and ran, the web page showed a circle all the time.
![1](https://github.com/thirdweb-dev/unity-sdk/assets/96010800/fbf82ca8-f87e-4be2-a6da-cbc81dd2198b)

**Comment by 0xFirekeeper** [comment]
Hey! Please check out our [Build Instructions](https://github.com/thirdweb-dev/unity-sdk?tab=readme-ov-file#build-instructions) for WebGL
