### ISSUE TITLE
Unable to find a constructor to use for type Nethereum.

### ISSUE THREAD

**Issue by haokunABC** [thirdweb-dev/unity-sdk#190]
When I build a project on the **Unity WebGL** platform and I run it on Chrome,In the method:
**BigInteger blocktimestamp = await Blocks.GetLatestBlockTimestamp();**
throw an exception.
The exception error content is:
1._Unable to find a constructor to use for type Nethereum.RPC.Eth.DTOs.BlockWithTransactionHashes. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'result.hash', line 1, position 18._
Error in another case:
2._Error retrieving blockchain timestamp: Error occurred when trying to send rpc requests(s): eth_blockNumber_
![image](https://github.com/thirdweb-dev/unity-sdk/assets/96010800/1ce430fa-6a01-4029-83a9-b1bbcaa8ebe0)

After I tried to update and add Nethereum.Web3 and Nethereum.Hex libraries, I got a new error:
3. _Error creating 'Nethereum.Hex.HexTypes.HexRPCTypeJsonConverter`2[Nethereum.Hex.HexTypes.HexBigInteger,System.Numerics.BigInteger]'_

**Comment by 0xFirekeeper** [comment]
Hey @haokunABC please see our Build Settings [here](https://github.com/thirdweb-dev/unity-sdk/tree/v4.14.0?tab=readme-ov-file#build-instructions) - in this case try turning on Minimal Stripping. If that doesn't do the trick, try adding the [linker](https://github.com/thirdweb-dev/unity-sdk/tree/v4.14.0?tab=readme-ov-file#miscellaneous) here.

**Comment by haokunABC** [comment]
> Hey @haokunABC please see our Build Settings [here](https://github.com/thirdweb-dev/unity-sdk/tree/v4.14.0?tab=readme-ov-file#build-instructions) - in this case try turning on Minimal Stripping. If that doesn't do the trick, try adding the [linker](https://github.com/thirdweb-dev/unity-sdk/tree/v4.14.0?tab=readme-ov-file#miscellaneous) here.
It worked, thank you very much!

**Comment by 0xFirekeeper** [comment]
You're welcome!
