### ISSUE TITLE
Main page having issues loading NFT metadata

### ISSUE THREAD

**Issue by mikedotexe** [thirdweb-dev/unity-sdk#191]
Wanted to report some issues with fetching NFT metadata.

<img width="1779" alt="Screenshot 2024-05-31 at 11 14 11 AM" src="https://github.com/thirdweb-dev/unity-sdk/assets/1042667/197329c4-3a84-4429-840b-2ab83e372b68">

I'm really excited about this SDK.

**Comment by 0xFirekeeper** [comment]
Try using a thirdweb client id in your ThirdwebManager if you aren't already. You can get one for free [here](https://thirdweb.com/create-api-key).

**Comment by 0xFirekeeper** [comment]
Just realized this is our preview build, needs updating thanks for the report!
