### ISSUE TITLE
createSessionKey is not a function

### ISSUE THREAD

**Issue by mikedotexe** [thirdweb-dev/unity-sdk#192]
Very excited about using 4337 and other AA stuff. Wanted to report seeing this:

<img width="1779" alt="Screenshot 2024-05-31 at 11 27 48 AM" src="https://github.com/thirdweb-dev/unity-sdk/assets/1042667/72dc224b-4f1f-4bd7-a385-0fd3b1949a4b">

**Comment by 0xFirekeeper** [comment]
Hey @mikedotexe , have you followed our WebGL [build instructions](https://github.com/thirdweb-dev/unity-sdk?tab=readme-ov-file#build-instructions)? If so can you please share the SDK version, thanks!

**Comment by 0xFirekeeper** [comment]
Just realized this is our preview build, needs updating thanks for the report!
