### ISSUE TITLE
Unity SDK Gateway

### ISSUE THREAD

**Issue by issihiki** [thirdweb-dev/unity-sdk#202]
I'm using the Third Web unity SDK, could you please tell me which IPFS gateway it uses by default?

**Comment by issihiki** [comment]
I want the URL of the gateway I'm referencing.

**Comment by 0xFirekeeper** [comment]
The gateway when using a client id is `https://{YOUR_CLIENT_ID}.ipfscdn.io/ipfs/`
Fallback if no client id is `https://cloudflare-ipfs.com/ipfs/`
Overrideable in the ThirdwebManager
