### ISSUE TITLE
WebGL Build Issue: " Cannot read properties of undefined (reading 'initialize') at _ThirdwebInitialize

### ISSUE THREAD

**Issue by CapdeO** [thirdweb-dev/unity-sdk#203]
# Message error from Brave browser
![Captura desde 2024-06-20 17-18-36](https://github.com/thirdweb-dev/unity-sdk/assets/103727616/2790ba5a-8442-4c7f-b603-c30e2517bf8d)

# Message error from Mozilla browser
![Captura desde 2024-06-20 17-20-24](https://github.com/thirdweb-dev/unity-sdk/assets/103727616/2fd9ae0b-83ea-4006-b949-dbad71b69107)

**Comment by CapdeO** [comment]
What are the dependencies that I need to have pre-installed in Unity to use the Unity SDK?

**Comment by CapdeO** [comment]
@0xFirekeeper Have you ever run into this problem? Do you know how to solve it? I am overwhelmed. I need to solve it to present my project in a hackathon

**Comment by 0xFirekeeper** [comment]
Hey @CapdeO ! You only need to use our WebGL Template in your Player Settings to fix this. Please see our Build Instructions [here](https://github.com/thirdweb-dev/unity-sdk?tab=readme-ov-file#build-instructions).
