### ISSUE TITLE
Cannot connect to metamask default chain

### ISSUE THREAD

**Issue by quurkyhongyu** [thirdweb-dev/unity-sdk#208]
When on sepolia test net, metamask can't connect due to it has to connected through "wallet_switchEthereumChain" and not "wallet_addEthereumChain". But inside the Blockchains.MetaMaskDefaults does not contains sepolia test net, so after comment the condition sanitisation then can work alr.

(we tested so far only arbitrum-sepolia can work)

```cs
        protected async Task ConnectWithDefaultChain()
        {
            var chainData =  #DefaultChainInfo;

            // after comment out this then can connect to metamask wallet, sepolia test net
            //if (Blockchains.MetaMaskDefaults.Contains((long)defaultChain))
            {
                await _wallet.ConnectWith<object>(RpcMethods.WalletSwitchEthereumChain,
                    new object[] { chainData.AsSwitchChainRequest() });
                return;
            }
            
            await _wallet.ConnectWith<object>(RpcMethods.WalletAddEthereumChain,
                new object[] { chainData });
        }
```

here is the error log in unity
[unitysdk-metamask-error.txt](https://github.com/user-attachments/files/16373039/unitysdk-metamask-error.txt)

Hope this will get fixed soon

**Comment by 0xFirekeeper** [comment]
Hi, this is being looked at as part of #207 and will likely be merged next week after some additional testing, apologies for the inconvenience.
