### ISSUE TITLE
Assembly 'Library/ScriptAssemblies/Assembly-CSharp.dll' will not be loaded due to errors: Reference has errors 'Thirdweb.Core'.

### ISSUE THREAD

**Issue by tuanle-varmeta** [thirdweb-dev/unity-sdk#210]
When I compile the script, I often get this error. This makes me have to close Unity and reopen it. Is there a way to solve it completely?

Assembly 'Library/ScriptAssemblies/Assembly-CSharp.dll' will not be loaded due to errors:
Reference has errors 'Thirdweb.Core'.

Unity Version: 2021.3.25f1

![image](https://github.com/user-attachments/assets/28423e0b-bc84-4361-9e98-7f65e0527f60)

**Comment by 0xFirekeeper** [comment]
Search for embedded-wallet (dll) in your project and untick auto-reference from Inspector
Seems like a Newtonsoft.Json conflict

**Comment by 0xFirekeeper** [comment]
Made that default in 4.19 package
