### ISSUE TITLE
Called Wallet.Sign() with this message on WebGL build, failed and got this error: invalid hexlify error

### ISSUE THREAD

**Issue by crmantow** [thirdweb-dev/unity-sdk#212]
The string i want to sign:

```csharp
string domain = "myDomain";
string chainId = "1";
string message = "Sign in";
string uri = "myUri";

string data = "{\"domain\":\"" + domain + "\",\"chainId\":" + chainId + ",\"message\":\"" + message + "\",\"wallet\":\"" + walletAddress + "\",\"nonce\":\"" + nonce + "\",\"uri\":\"" + uri + "\"}";
return await sdk.Wallet.Sign(data);
```

**Comment by 0xFirekeeper** [comment]
You can try copying this code for SIWE https://github.com/thirdweb-dev/unity-sdk/blob/dafafeaaf343d3de6c934212c0fe4bac662bc537/Assets/Thirdweb/Core/Scripts/Wallet.cs#L136-L149

Or use v5 Utils.GenerateSIWE

**Comment by crmantow** [comment]
I'm encountering an invalid hexify error when including the chainId in the JSON data string, but the error disappears when I exclude it. Is there a specific reason for this behavior?
Because i need to sign using that format.
