### ISSUE TITLE
Exception: Websocket closed with ServerError code

### ISSUE THREAD

**Issue by kynesss** [thirdweb-dev/unity-sdk#213]
Hello, on the android build when connecting to the WebSocket wallet, the WebSocket itself disconnects and throws this exception: 

Exception: Websocket closed with ServerError code
WalletConnectSharp.Network.JsonRpcProvider.Request[T,TR] (WalletConnectSharp.Network.IRequestArguments`1[T] requestArgs, System.Object context) (at <c8565b85967e4ea0ad510535fa57b4f9>:0)
WalletConnectSharp.Core.Controllers.Relayer.Request[T,TR] (WalletConnectSharp.Network.IRequestArguments`1[T] request, System.Object context) (at <7537f265f1f94bc9af6f13f93196cba8>:0)
WalletConnectSharp.Core.Controllers.Publisher.Publish (WalletConnectSharp.Core.Models.Publisher.PublishParams params) (at <7537f265f1f94bc9af6f13f93196cba8>:0) 

Literally once in maybe 10 attempts I was able to connect with Metamask. I was using the latest available version of the SDK v5.0.0. Can I ask for possible help or at least a reason why this is happening? Thank you in advance.

**Comment by laalauren1** [comment]
@kynesss You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID 07638
Please see the link below to our dedicated support line:
[Metamask live support](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by 0xFirekeeper** [comment]
Hi, could you open an issue in the official WalletConnectUnity repo with [bug report template](https://github.com/WalletConnect/WalletConnectUnity/issues/new?assignees=&labels=bug&projects=&template=%F0%9F%90%9E-bug-report.md&title=) and provide WC project id if you've overriden the default thirdweb one?

**Comment by 0xFirekeeper** [comment]
Working with the WalletConnect team to get this fixed, will push a couple updates to their sdk in the meantime, thanks for reporting
