### ISSUE TITLE
Can we enable Valora Wallet for mobile and Celo Opera Minipay Wallet for Desktop Browsers & mobile?

### ISSUE THREAD

**Issue by lopeselio** [thirdweb-dev/unity-sdk#214]
Many Celo ecosystem projects might want to integrate with widely used mobile wallets - and will be a helpful starting point. Thanks

- [Valora](https://valora.xyz/)
- [MiniPay](https://www.opera.com/products/minipay)

**Comment by 0xFirekeeper** [comment]
Have you tried connecting with [WalletConnect](https://portal.thirdweb.com/unity/v5/wallets/walletconnect)? Valora should be supported https://explorer.walletconnect.com/valora
Unsure about MiniPay, we'll look into it - I believe we're already in talks with Celo to expand the offering there.

**Comment by lopeselio** [comment]
The game is built on unity for mobile - so we wouldn't be able to scan the QR from Valora mobile app. We need to enable deep-links internally to establish the connections. Valora only has a react native SDK and no tooling for unity yet

**Comment by 0xFirekeeper** [comment]
Valora does have [deeplinking](https://explorer-api.walletconnect.com/v3/all?projectId=2f05ae7f1116030fde2d36508f472bfb&ids=d01c7758d741b363e637a817a09bcf579feae4db9f5bb16f599fdd1f66e2f974) from WalletConnect, as long as you build for Android the behavior will be to deeplink
![45797d3e0569a6c35b00b0c7ff8e94f4](https://github.com/user-attachments/assets/a7a57755-6229-40f2-8996-7409d081f200)

**Comment by lopeselio** [comment]
I see - how can we enable account abstraction with external wallets like Valora?

**Comment by 0xFirekeeper** [comment]
You can pass `SmartWalletOptions` to `ThirdwebManager.Instance.ConnectWallet`, or alternatively call `ThirdwebManager.Instance.UpgradeToSmartWallet`. All wallet providers can be the signer of a Smart Wallet, unlocking AA.

**Comment by lopeselio** [comment]
So while testing on unity editor, any transaction from a game running on PC - would invoke a transaction confirmation/signature UI inside Valora app on mobile right?

**Comment by 0xFirekeeper** [comment]
Yes
