### ISSUE TITLE
Use Unity Newtonsoft Json instead or other json library

### ISSUE THREAD

**Issue by BoysheO** [thirdweb-dev/unity-sdk#217]
Unity IAP relies on Unity's custom package com.unity.nuget.newtonsoft-json, whose API differs from the official version of Newtonsoft. Since the ThirdWeb SDK includes a version of the package located at Assets\Thirdweb\Runtime\Newtonsoft.Json, installing com.unity.purchasing causes the following compilation error:

```
Library\PackageCache\com.unity.services.core@1.12.5\Editor\Core\Environments\Client\Http\JsonHelpers.cs(26,13): error CS0103: The name 'AotHelper' does not exist in the current context
```

For more information, please refer to: https://discussions.unity.com/t/aothelper-compilation-error-when-installing-unity-services-packages/924194

My solution is to delete the Assets\Thirdweb\Runtime\Newtonsoft.Json.13.0.3 folder, which prompts Unity to use the com.unity.nuget.newtonsoft-json package, thereby resolving the issue. I have not thoroughly tested the solution's impact on the SDK yet, but I will report any updates here.

**Comment by 0xFirekeeper** [comment]
There is no impact, most versions of Newtonsoft.Json will work with our sdk, our [Getting Started](https://github.com/thirdweb-dev/unity-sdk?tab=readme-ov-file#getting-started) also mentions you are free to deselect such utilities if you already have them, no worries!
