### ISSUE TITLE
v5.9.0 WebGL Android Mobile Browser - Connect Feature - `window.ethereum is undefined` causing Metamask Deeplink Not Working

### ISSUE THREAD

**Issue by quurkyhongyu** [thirdweb-dev/unity-sdk#219]
The window.ethereum is undefined on mobile browser, therefore before the Connect try to switch ethereum chain, it failed to get the instance and return false

The code below is from `MetaMaskWallet.cs` & `WebGLMetaMask.jslib`, I believe the jslib function below to check the wallet was existed or not in browser. But I think it is not for case like webgl mobile browser;

```cs
// MetaMaskWallet.cs
if (metaMaskInstance.IsMetaMaskAvailable())
{
    // switch to ethereum network...
}
else
{
    throw new Exception("MetaMask is not available.");
}
```

```cs
// WebGLMetaMask.cs
public async Task<T> RequestAsync<T>(RpcRequest rpcRequest)
{
    var rpcRequestMessage = JsonConvert.SerializeObject(rpcRequest);
    _rpcResponseCompletionSource = new TaskCompletionSource<string>();
    
#if UNITY_WEBGL && !UNITY_EDITOR
    Request(rpcRequestMessage, gameObject.name, nameof(OnRequestCallback), nameof(OnRequestFallback));
#endif

    var response = await _rpcResponseCompletionSource.Task;
    var rpcResponseRaw = JsonConvert.DeserializeObject<RpcResponse<T>>(response);
    if (rpcResponseRaw.Error != null)
    {
        throw new Exception(rpcResponseRaw.Error.Message);
    }
    return rpcResponseRaw.Result;
}
```
 
```js
// WebGLMetaMask.jslib
IsMetamaskAvailable: function () {
  return window.ethereum ? true : false;
}
  ```

**Comment by warengonzaga** [comment]
Hello @quurkyhongyu, we received your ticket, and I'm tagging @0xFirekeeper for an extra eye and explanation about this. However, we recommend using native builds for mobile instead of using WebGL for your mobile app, as this is a known issue.

**Comment by 0xFirekeeper** [comment]
Marked this as a feature request internally, we don't officially support external wallets on webgl mobile for the time being.
