### ISSUE TITLE
latest release installs, then errors AotHelper does not exist

### ISSUE THREAD

**Issue by 57u** [thirdweb-dev/unity-sdk#221]
After installing the latest release, on Mac Unity 6000.0.23f1, the following errors show immediately:

```Library/PackageCache/com.unity.services.core/Editor/Core/Environments/Client/Http/JsonHelpers.cs(26,13): error CS0103: The name 'AotHelper' does not exist in the current context

Library/PackageCache/com.unity.services.core/Editor/Core/Environments/Client/Http/JsonHelpers.cs(27,13): error CS0103: The name 'AotHelper' does not exist in the current context
```

Is there some sort or prerequisite i missed?

**Comment by 0xFirekeeper** [comment]
You might have multiple versions of Json.NET / Newtonsoft.Json, likely from one of the unity packages
Feel free to delete our Newtonsoft.Json DLL if it conflicts, as mentioned [here](https://github.com/thirdweb-dev/unity-sdk?tab=readme-ov-file#getting-started)

**Comment by BoysheO** [comment]
see https://github.com/thirdweb-dev/unity/issues/217.
