### ISSUE TITLE
unity2020.3.44, a new test project imports apha-2.0 package then has these errors!

### ISSUE THREAD

**Issue by flyarong** [thirdweb-dev/unity-sdk#44]
Assets\Thirdweb\Plugins\WalletConnectSharp.Core\Models\Ethereum\Types\EvmTypedData.cs(20,17): error CS8124: Tuple must contain at least two elements.

Assets\Thirdweb\Plugins\WalletConnectSharp.Core\WalletConnectSession.cs(501,67): error CS1026: ) expected

Assets\Thirdweb\Plugins\WalletConnectSharp.Core\WalletConnectSession.cs(501,70): error CS1002: ; expected

Assets\Thirdweb\Plugins\WalletConnectSharp.Core\WalletConnectSession.cs(501,88): error CS1002: ; expected

Assets\Thirdweb\Plugins\WalletConnectSharp.Core\WalletConnectSession.cs(501,88): error CS1513: } expected

Assets\Thirdweb\Plugins\WalletConnectSharp.Core\WalletConnectSession.cs(501,89): error CS1002: ; expected

Assets\Thirdweb\Plugins\WalletConnectSharp.Core\WalletConnectSession.cs(504,22): error CS8641: 'else' cannot start a statement.

Assets\Thirdweb\Plugins\WalletConnectSharp.Core\WalletConnectSession.cs(504,22): error CS1003: Syntax error, '(' expected

Assets\Thirdweb\Plugins\WalletConnectSharp.Core\WalletConnectSession.cs(504,22): error CS1525: Invalid expression term 'else'

Assets\Thirdweb\Plugins\WalletConnectSharp.Core\WalletConnectSession.cs(504,22): error CS1026: ) expected

Assets\Thirdweb\Plugins\WalletConnectSharp.Core\WalletConnectSession.cs(504,22): error CS1002: ; expected

Assets\Thirdweb\Plugins\WalletConnectSharp.Core\WalletConnectSession.cs(510,13): error CS1519: Invalid token ')' in class, struct, or interface member declaration

Assets\Thirdweb\Plugins\WalletConnectSharp.Core\WalletConnectSession.cs(512,32): error CS1519: Invalid token '=' in class, struct, or interface member declaration

Assets\Thirdweb\Plugins\WalletConnectSharp.Core\WalletConnectSession.cs(516,32): error CS1519: Invalid token '=' in class, struct, or interface member declaration

Assets\Thirdweb\Plugins\WalletConnectSharp.Core\WalletConnectSession.cs(518,28): error CS1519: Invalid token ';' in class, struct, or interface member declaration

Assets\Thirdweb\Plugins\WalletConnectSharp.Core\WalletConnectSession.cs(683,1): error CS1022: Type or namespace definition, or end-of-file expected

**Comment by 0xFirekeeper** [comment]
Will test and fix on 2020, please use v2021 meanwhile, thanks for the report!

**Comment by flyarong** [comment]
Thanks for the answer。Will there support WalletConnectCSharp V2.0?

**Comment by 0xFirekeeper** [comment]
There are plans to support v2.0, yes
