### ISSUE TITLE
Error during calling the first transaction after switching networks successfully

### ISSUE THREAD

**Issue by 0xFirekeeper** [thirdweb-dev/unity-sdk#5]
![image](https://user-images.githubusercontent.com/43042585/204174496-453abcee-8e34-4c89-88f7-92d738824d97.png)
When you switch networks after connecting, the next transaction throws an error.
> ThirdwebSDK invoke error Error: underlying network changed (event="changed", network={"chainId":10,"name":"unknown"}, detectedNetwork={"name":"homestead","chainId":1,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"}, code=NETWORK_ERROR, version=providers/5.2.0)

**Comment by joaquim-verges** [comment]
just fixed this on main (will release soon)
