### ISSUE TITLE
please help me.

### ISSUE THREAD

**Issue by flyarong** [thirdweb-dev/unity-sdk#55]
follow  the tutorial of https://blog.thirdweb.com/guides/add-a-connect-wallet-button-in-a-unity-game/.
get the errors in  Unity2022.1.23 and alpha3 version:
NullReferenceException: Object reference not set to an instance of an object
Thirdweb.Wallet.Connect (System.Nullable`1[T] walletConnection) (at Assets/Thirdweb/Core/Scripts/Wallet.cs:41)
StartMenuManager.ConnectWallet () (at Assets/CSharpScript/StartMenuManager.cs:28)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <252f5a151e57406087568ebdeb88d5fe>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <f7bcd9bfa40c4821acdda68a85850616>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <f7bcd9bfa40c4821acdda68a85850616>:0)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <f7bcd9bfa40c4821acdda68a85850616>:0)

my Code:
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Thirdweb; // for interacting with the SDK
using System.Threading.Tasks; // for some async functionality

public class StartMenuManager : MonoBehaviour
{
    public GameObject ConnectedState;
    public GameObject DisconnectedState;
    private ThirdwebSDK sdk;
    // Start is called before the first frame update
    void Start()
    {
        // Configure the network you deployed your contracts to:
        sdk = new ThirdwebSDK("goerli",5);

    }

    // Update is called once per frame
    void Update()
    {
        
    }
    public async void ConnectWallet()
    {
        // Connect to the wallet
        string address =
            await sdk
                .wallet
                .Connect(new WalletConnection()
                {
                    provider = WalletProvider.CoinbaseWallet,
                    chainId = 5 // Switch the wallet Goerli on connection
                });

        // Disable disconnected state
        DisconnectedState.SetActive(false);

        // Enable connected state
        ConnectedState.SetActive(true);

        // Set the ConnectedStates "Address" GameObjects text to the wallet address
        ConnectedState
          .transform
          .Find("Address")
          .GetComponent<TMPro.TextMeshProUGUI>()
          .text = address;
    }
}

**Comment by 0xFirekeeper** [comment]
Please refer to our example scene and see if you can build it. 
For WebGL you must create a build to test, the editor uses the native set of functions which require a ThirdwebManager in your scene. 
Finally, try following newer guides as our 2.0 version has breaking changes.
