### ISSUE TITLE
walletconnect is unstable

### ISSUE THREAD

**Issue by Morisander** [thirdweb-dev/unity-sdk#59]
i am working with the version2 plugin of yours now since the first alpha came out and tried every version since.
the problem seems to be, that the walletconnect part seems to be unstable somehow, as it most of the time is does not connect the wallet, but lets it be in a loading screen (tried several wallets for this, all the same, either no reaction or a infinite loading). sometimes it works, but to get to this point i need to close, reopen and rescan the modal several times.
same for the example scene as well as selfmade scenes with own scripts and the thirdweb manager.

**Comment by 0xFirekeeper** [comment]
Identified the issue, will be fixed next release, thank you Morisander!
