### ISSUE TITLE
Error parsing return type solidity Struct[]

### ISSUE THREAD

**Issue by 0xFirekeeper** [thirdweb-dev/unity-sdk#6]
![image](https://user-images.githubusercontent.com/43042585/204174740-4c5f9604-a61f-4f4c-a06d-c10d56417e2d.png)
Expected but worth mentioning, solidity returning [[struct],[struct]] for struct arrays is not parseable, would like to get the raw string result in this case if no other option is possible.

**Comment by joaquim-verges** [comment]
@0xFirekeeper what are you deserializing the result as? I would imagine you would call it like
```csharp
var result = await contract.Read<List<MyStruct>>("someFunction");
```
that would be for a simple struct array, and for array of arrays I imagine something like
```csharp
var result = await contract.Read<List<List<MyStruct>>>("someFunction");
```
should work?

the unexpected character is weird though, would love to see the entire string value it's trying to parse

**Comment by 0xFirekeeper** [comment]
@joaquim-verges The result string is highlighted on the right hand side of the screenshot.

When parsing into a List<List<MyStruct>>> it shows this

Exception: One or more errors occurred. (Error converting value False to type 'JsonData_SHOP'. Path 'result[0][0]', line 1, position 17.)

The problem is the result is an array of arrays of non-json objects I guess, so would need to parse it into List<List<type1,type2,etc>>> which won't work with a predefined struct, will try with List<MyStruct> where MyStruct contains an array of the value types, think that might work..

**Comment by 0xFirekeeper** [comment]
Solved by parsing into List<List<object>>
