### ISSUE TITLE
update newtonsoft dependency to 3.1.0

### ISSUE THREAD

**Issue by JayPerfetto** [thirdweb-dev/unity-sdk#60]
If you include the newtonsoft dependency when importing this package, it causes conflicts with the 3.1.0 version that is used by unity registry projects. If you omit it, the versions don't match so the dependency doesn't resolve in the plugin's using statements

**Comment by 0xFirekeeper** [comment]
@JayPerfetto as long as you have Newtonsoft in your package, feel free to remove yours or ours. After that, if you have plugins (dlls) that rely on a specific version, unity allows you to select the plugin and uncheck Validate References to fix the issue.
