### ISSUE TITLE
WebScoket Errors 

### ISSUE THREAD

**Issue by alibk1** [thirdweb-dev/unity-sdk#65]
When I intergrate unitypackage, Unity gives me 3 errors like:

1-
Assets\Thirdweb\Plugins\WalletConnectSharp.Unity\Network\NativeWebSocketTransport.cs(157,47): error CS0433: The type 'WebSocketCloseCode' exists in both 'NativeWebSocket, Version=0.0.2.0, Culture=neutral, PublicKeyToken=null' and 'endel.nativewebsocket, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

2-
Assets\Thirdweb\Plugins\WalletConnectSharp.Unity\Network\NativeWebSocketTransport.cs(22,17): error CS0433: The type 'WebSocket' exists in both 'NativeWebSocket, Version=0.0.2.0, Culture=neutral, PublicKeyToken=null' and 'endel.nativewebsocket, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

3-
Assets\Thirdweb\Plugins\WalletConnectSharp.Unity\Network\NativeWebSocketTransport.cs(23,17): error CS0433: The type 'WebSocket' exists in both 'NativeWebSocket, Version=0.0.2.0, Culture=neutral, PublicKeyToken=null' and 'endel.nativewebsocket, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

**Comment by 0xFirekeeper** [comment]
It sounds like you have a duplicate package in your project, you can delete one of the duplicates highlighted when you click on the error. Is this a fresh project? Please specify the unity version to repro as well.
