### ISSUE TITLE
IT'S NOT AN ISSUE JUST A QUESTION

### ISSUE THREAD

**Issue by alibk1** [thirdweb-dev/unity-sdk#67]
Hi developers,

Sorry for my amateurism. I am new at NFTs and Cryptocoins.

Well, I am developing an app which creates random scenes with random assets and then allows taking screenshots to users so my users will have random and probably unique photos to sell them as NFTs. But my client asked me to add Solana and Metamask to this project and allow users to connect their wallets and own the photos the downloaded as NFTs in their wallets.

System will process like this: Users will connect to wallets > Press "Select" button to select any jpg file from their gallery (this photo will be downloaded in our app) > Then press "Send it to wallet" button and mint the selected jpg file as NFT in their wallet.

So, I have already handled the downloading created images part. In your video series, connecting to a wallet part is done too. Also, I can handle picking any jpg file from gallery part. So, I just need to know how to mint a normal jpg file to NFT and send it to users wallet. 

Iı don't want to steal your time for deetailed explanation. So, if there is any useful link or step by step sshort explanation, I will be greatful. I really need an answer. Thank you

**Comment by 0xFirekeeper** [comment]
Hey, I think our support discord is the best place to ask such questions - we have a lot of resources there. You can check out our example scene on how to upload a screenshot to IPFS and then you can call one of our mint functions with that token URI.
