### ISSUE TITLE
Error Fetching Native Balance: Error occurred when trying to send rpc 

### ISSUE THREAD

**Issue by alibk1** [thirdweb-dev/unity-sdk#69]
I have 2 projects. One of them is for testing other is release version. Whatever, I have imported your sdk to test project and then modified the scene. There is only one problem in test project, i will submit it later.

Whatever, in the test project , i can succesfully connect to MetaMask wallet. But in the release version, i tap to the connect button it  goes to MetaMask app and returns and I am getting this error:

Error Fetching Native Balance: Error occurred when trying to send rpc requests(s): eth_getBalance
<OnConnected>d__31:MoveNext()
System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start(TStateMachine&)
Prefab_ConnectWalletNative:OnConnected()
<OnConnect>d__30:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(TResult)
Thirdweb.<Connect>d__1:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(TResult)
WalletConnectSharp.Unity.<WalletSwitchEthChain>d__43:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(TResult)
WalletConnectSharp.Core.<WalletSwitchEthChain>d__53:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(TResult)
WalletConnectSharp.Core.<Send>d__60`2:MoveNext()
System.Threading.Tasks.TaskCompletionSource`1:SetResult(TResult)
WalletConnectSharp.Core.Events.EventDelegator:Trigger(String, String)
WalletConnectSharp.Core.<TransportOnMessageReceived>d__58:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(TResult)
WalletConnectSharp.Core.Network.<DecryptWithKey>d__1:MoveNext()
UnityEngine.UnitySynchronizationContext:Exec()

All the process is the same with test project. So I could not detect what the problem is. What should I do?

**Comment by 0xFirekeeper** [comment]
Seen on Discord, we can continue there.
