### ISSUE TITLE
Request: Add value param to Contract.Write API

### ISSUE THREAD

**Issue by 0xFirekeeper** [thirdweb-dev/unity-sdk#7]
Would be nice to be able to use that API for payables instead of SendRawTransaction which is a bit harder to use.

**Comment by joaquim-verges** [comment]
just merged a change to enable this. Overloaded the `contract.Write` function to pass a TransactionRequest object, looks like this:

```csharp
await contract.Write("claim", new TransactionRequest
{
    value = "50000000000000000" // 0.05 ETH
}, receiverAddress, tokenId, quantity);
```

you can also override gas limit, price, etc.

Next step is to make it easier to work with wei values, will add some util functions for it
