### ISSUE TITLE
Minor Request: Pass contract interaction exception message to thirdweb sdk exception message

### ISSUE THREAD

**Issue by 0xFirekeeper** [thirdweb-dev/unity-sdk#8]
Currently, most exception messages are visible and can be shown to the user.

When writing to a contract, when either:
1) Closing the tx popup
2) Unable to estimate gas (revert expected)

The message on the caught exception on Unity's end from the SDK is either 1) empty or 2) does not include the revert error
PS: The actual error message can be sometimes found in the raw error message logged in the console.

**Comment by joaquim-verges** [comment]
I just fixed this (needed a change in the JS SDK) and propagated it back up to C# (on latest main) give it a run!

**Comment by 0xFirekeeper** [comment]
Perfect thanks!
