### ISSUE TITLE
How to provide the signer in Unity?

### ISSUE THREAD

**Issue by 7-Qin** [thirdweb-dev/unity-sdk#82]
Error shows:
ThirdwebSDK invoke error Error: Cannot create a transaction without a signer. Please ensure that you have a connected signer.
Exception: Cannot create a transaction without a signer. Please ensure that you have a connected signer.

**Comment by 7-Qin** [comment]
![image](https://github.com/thirdweb-dev/unity-sdk/assets/51499424/e1f47de9-e513-4317-a517-105aa4533c10)

**Comment by 7-Qin** [comment]
I think probably I connect the wallet in a Scene and use the MINT function in another Scene?

**Comment by 0xFirekeeper** [comment]
Use the ThirdwebManager prefab to ensure connectivity remains accross scenes.
