### ISSUE TITLE
WalletConnect connection success no callback

### ISSUE THREAD

**Issue by mdjzs** [thirdweb-dev/unity-sdk#84]
![1687625440635](https://github.com/thirdweb-dev/unity-sdk/assets/76468044/cb2c2d86-7bfc-4f78-85da-0903c82d60b9)
WalletConnect connection success,but "OnConnectedCallback" not executed

**Comment by 0xFirekeeper** [comment]
Can you try this with the latest release/new Prefab_ConnectWallet? The callback should work as long as you've added an event listener from the inspector or code.
