### ISSUE TITLE
Function parameter serialization for webGL will fail

### ISSUE THREAD

**Issue by AwsmKonstantin** [thirdweb-dev/unity-sdk#86]
Hi all! When attempting to call a write operation on a smart contract in a webGL build I was running into an overflow exception in a BigInteger parameter.

To reproduce the issue:
1. Create a contract with a custom ABI, that has a ERC20 compatible "transfer" function
2. Invoke write method on the "transfer" function and transfer over 1ETH of tokens

I've traced it to the following issue:

In Thirdweb/Core/Scripts/Contract.cs
In Write() method when creating the body argument SDK is passing args "as is" to the Utils.ToJsonStringArray()

`return await Bridge.InvokeRoute<TransactionResult>(getRoute("call"), Utils.ToJsonStringArray(functionName, args, transactionOverrides));`

The issue is that since "args" is an array, the SDK will invoke a simple JsonConvert.SerializeObject(). In case of BigInteger it seems to produce a representation that js will attempt to parse as a "number" which in turn will cause an overflow.

The solution is to force convert "args" to a string array, so that the line above becomes:
`return await Bridge.InvokeRoute<TransactionResult>(getRoute("call"), Utils.ToJsonStringArray(functionName, Utils.ToJsonStringArray(args), transactionOverrides));`

Secondly I needed to ensure that BigInteger would invoke its ToString() method so in Utils.ToJsonStringArray I've modified
`
if (args[i].GetType().IsPrimitive || args[i] is string )
{
    stringArgs.Add(args[i].ToString());
}
`
to this
`
if (args[i].GetType().IsPrimitive || args[i] is string || args[i] is BigInteger)
{
    stringArgs.Add(args[i].ToString());
}
`

**Comment by 0xFirekeeper** [comment]
Hm I don't see issues with your changes at first glance, could you open a PR for review? Thanks!
