### ISSUE TITLE
Request: Remove the webgl template loading screen

### ISSUE THREAD

**Issue by 0xFirekeeper** [thirdweb-dev/unity-sdk#9]
The custom loading screen the sdk comes with interferes with the loading flow, Unity has logo/splash and if not premium, "Made with Unity" screens already, another screen before that is a bit too much imo.

**Comment by joaquim-verges** [comment]
The problem is that it takes a little while to load the js SDK + creating the unity instance.

How about just leaving the indeterminate spinner just so we have something showing up immediately (instead of a black screen)?

**Comment by 0xFirekeeper** [comment]
Yes that's a good compromise!
