### ISSUE TITLE
Metamask connection not working when build the game

### ISSUE THREAD

**Issue by savasadar** [thirdweb-dev/unity-sdk#90]
I am using metamask connection type for connect to the game and everything is working on editor. But When I get build for windows, I am seeing QR but wallet can't connect this QR. So Metamask connection is not working on release build.

**Comment by 0xFirekeeper** [comment]
Can't seem to replicate when building Scene_Prefabs to Windows.

Please provide more information about your setup and logs to help debug.

**Comment by savasadar** [comment]
I changed **building backend** as `mono` instead of `IL2CPP` from **player settings**. And it is working now but too unstable sometimes never trigger to wallet or stack loading screen on wallet.(probably this is about metamask socket connections)

**Comment by Thomas107500** [comment]
Encountered similar problem, my app is an Android app, i build it using mono (can confirm IL2CPP crash the app, more detail below) i used the connect wallet prefab, the qr code and the buttons are all responsive, the deeplink successfully opened metamask on my phone, metamask did show connecting message, but then it just disappeared, no asking me to sign anything, i waited a few seconds then close the metamask app and switched back to my app, it didnt crash but nothing happened, there are a few occasions my app suddenly opened metamask and the it ask me to allow access, i allowed access and back to app the qr code screen did disappear, but the connect wallet button did not change to the UI component that display balance etc.

Here is the log i get when running on my phone
![image](https://github.com/thirdweb-dev/unity-sdk/assets/49201909/3da45e21-29f1-4777-805a-fcfe973a31e6)

For IL2CPP, it will crash after i come back to the app after deeplink opened metamask, no option to sign in metamask either

**Comment by 0xFirekeeper** [comment]
We're aware of the issues on mobile and have updated the MM SDK, however wallet pausing/disconnection/crashing issues remain so we haven't [shipped it]](https://github.com/thirdweb-dev/unity-sdk/pull/101). We're in communication with the Metamask team to get it resolved.
